# Site settings
author: Anthony Lepore
title: Anthony Lepore
header-img: img/home-bg.png
email: violacellonyc@gmail.com
copyright_name: Anthony Lepore
description: > # this means to ignore newlines until "baseurl:"
  Anthony Lepore
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ViolaCello

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
